dependencies:
  - name: sidecarInjectorWebhook
    version: 1.0.1
    repository: file://./helm-charts/sidecarInjectorWebhook
    condition: sidecarInjectorWebhook.enabled
  - name: security
    version: 1.0.1
    repository: file://./helm-charts/security
    condition: security.enabled
  - name: ingress
    version: 1.0.1
    repository: file://./helm-charts/ingress
    condition: ingress.enabled
  - name: gateways
    version: 1.0.1
    repository: file://./helm-charts/gateways
    condition: gateways.enabled
  - name: mixer
    version: 1.0.1
    repository: file://./helm-charts/mixer
    condition: mixer.enabled
  - name: pilot
    version: 1.0.1
    repository: file://./helm-charts/pilot
    condition: pilot.enabled
  - name: grafana
    version: 1.0.1
    repository: file://./helm-charts/grafana
    condition: grafana.enabled
  - name: prometheus
    version: 1.0.1
    repository: file://./helm-charts/prometheus
    condition: prometheus.enabled
  - name: servicegraph
    version: 1.0.1
    repository: file://./helm-charts/servicegraph
    condition: servicegraph.enabled
  - name: tracing
    version: 1.0.1
    repository: file://./helm-charts/tracing
    condition: tracing.enabled
  - name: galley
    version: 1.0.1
    repository: file://./helm-charts/galley
    condition: galley.enabled
  - name: kiali
    version: 1.0.1
    repository: file://./helm-charts/kiali
    condition: kiali.enabled
  - name: certmanager
    version: 1.0.1
    repository: file://./helm-charts/certmanager
    condition: certmanager.enabled
