# Default values for kubeless.
## RBAC configuration
rbac:
  create: false

## Controller configuration
controller:
  deployment:
    replicaCount: 1
    image:
      repository: bitnami/kubeless-controller@sha256
      tag: 59007ec732c9957ce4b009c0b61d89ef0566b19b0751c11249afb88b38bd9830
      pullPolicy: IfNotPresent
  ## Kubeless Controller resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 500m
    #   memory: 512Mi

## UI configuration
ui:
  deployment:
    replicaCount: 1
    ui:
      image:
        repository: bitnami/kubeless-ui
        tag: v0.1.0
        pullPolicy: IfNotPresent
    proxy:
      image:
        repository: kelseyhightower/kubectl
        tag: 1.4.0
        pullPolicy: IfNotPresent

  service:
    name: ui-port
    type: NodePort
    externalPort: 3000

## Zookeeper configuration
zookeeper:
  statefulSet:
    replicaCount: 1
    image:
      repository: bitnami/zookeeper@sha256
      tag: f66625a8a25070bee18fddf42319ec58f0c49c376b19a5eb252e6a4814f07123
      pullPolicy: IfNotPresent
  ## Zookeeper server resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 500m
    #   memory: 512Mi

## Kafka configuration
kafka:
  statefulSet:
    replicaCount: 1
    image:
      repository: bitnami/kafka@sha256
      tag: ef0b1332408c0361d457852622d3a180f3609b9d98f1a85a9a809adaecfe9b52
      pullPolicy: IfNotPresent
  ## Kafka server resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 512Mi
    # requests:
    #   cpu: 500m
    #   memory: 512Mi
