apiVersion: v1
description: Istio Helm chart for Kubernetes
name: istio
version: 0.3.6
appVersion: 0.1.6
home: https://istio.io/
icon: http://trusted-charts-logos.stackpoint.io/istio.png
sources:
  - https://github.com/istio/istio
maintainers:
  - name: lachie83
    email: lachlan.evenson@microsoft.com
keywords:
- mesh
- routing
- load balancing
- experimental
