dependencies:
  - name: sidecarInjectorWebhook
    version: 0.8.0
    repository: file://./helm-charts/sidecarInjectorWebhook
    condition: sidecarInjectorWebhook.enabled
  - name: security
    version: 0.8.0
    repository: file://./helm-charts/security
    condition: security.enabled
  - name: ingress
    version: 0.8.0
    repository: file://./helm-charts/ingress
    condition: ingress.enabled
  - name: ingressgateway
    version: 0.8.0
    repository: file://./helm-charts/ingressgateway
    condition: ingressgateway.enabled
  - name: egressgateway
    version: 0.8.0
    repository: file://./helm-charts/egressgateway
    condition: egressgateway.enabled
  - name: mixer
    version: 0.8.0
    repository: file://./helm-charts/mixer
    condition: mixer.enabled
  - name: pilot
    version: 0.8.0
    repository: file://./helm-charts/pilot
    condition: pilot.enabled
  - name: grafana
    version: 0.1.0
    repository: file://./helm-charts/grafana
    condition: grafana.enabled
  - name: prometheus
    version: 0.1.0
    repository: file://./helm-charts/prometheus
    condition: prometheus.enabled
  - name: servicegraph
    version: 0.1.0
    repository: file://./helm-charts/servicegraph
    condition: servicegraph.enabled
  - name: tracing
    version: 0.1.0
    repository: file://./helm-charts/tracing
    condition: tracing.enabled
  - name: galley
    version: 0.8.0
    repository: file://./helm-charts/galley
    condition: galley.enabled
