dependencies:
  - name: sidecar-injector
    version: 0.5.0
    repository: file://../charts/sidecar-injector
    condition: sidecar-injector.enabled
  - name: ingress
    version: 0.5.0
    repository: file://../charts/ingress
    condition: ingress.enabled
  - name: mixer
    version: 0.5.0
    repository: file://../charts/mixer
    condition: mixer.enabled
  - name: pilot
    version: 0.5.0
    repository: file://../charts/pilot
    condition: pilot.enabled
  - name: security
    version: 0.5.0
    repository: file://../charts/security
    condition: global.securityEnabled
  - name: grafana
    version: 0.1.0
    repository: file://../charts/grafana
    condition: grafana.enabled
  - name: prometheus
    version: 0.1.0
    repository: file://../charts/prometheus
    condition: prometheus.enabled
  - name: servicegraph
    version: 0.1.0
    repository: file://../charts/servicegraph
    condition: servicegraph.enabled
  - name: zipkin
    version: 0.1.0
    repository: file://../charts/zipkin
    condition: zipkin.enabled
