# Default values for haddock.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: gcr.io/stackpoint-public/haproxy-ingress-controller
  tag: 0.1.8
  pullPolicy: IfNotPresent

rbac:
  enabled: true

deployment:
  # Whether to expose the service ports 80/443 on the host, hostPort requires a modern CNI
  useHostPort: true
  # hostnetworking avoids CNI problems, but must be false for use with networkpolicy
  hostNetwork: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  # if bound to the master and (hostNetwork|hostPort)=true, replicas must be < master count
  replicas: 1
  revisionHistoryCount: 2
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi


# If service.enabled == false, no service will be defined, and the ingressController
# will only be available on the pod hostPorts
service:
  enabled: false
  name: spc-balancer
  type: NodePort
  nodePort: 30080
  nodeTlsPort: 30443

# Install prometheus metrics service
metrics:
  enabled: false
  image:
    repository: quay.io/prometheus/haproxy-exporter
    tag: v0.9.0
    pullPolicy: IfNotPresent
  servicemonitor:
    label: metrics
    value: enabled
