name: gitlab-runner
version: 0.1.35
description: GitLab Runner
keywords:
- git
- ci
- cd
- deploy
sources:
- https://hub.docker.com/r/gitlab/gitlab-runner/
- https://docs.gitlab.com/runner/
icon: http://trusted-charts-logos.stackpoint.io/gitlab-runner.png
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
- name: DJ Mountney
  email: dj@gitlab.com
