apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-apiserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maya-apiserver
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: maya-apiserver
        image: "{{ .Values.apiserver.image }}:{{ .Values.apiserver.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: 
        - containerPort: 5656
        env:
        - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
          value: {{ .Values.jiva.image }}
        - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
          value: {{ .Values.jiva.image }}
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "{{ .Values.policies.monitoring.image }}"
        - name: OPENEBS_IO_JIVA_REPLICA_COUNT
          value: "{{ .Values.jiva.replicas }}"
