apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openebs-provisioner
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openebs-provisioner
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: openebs-provisioner
        image: "{{ .Values.provisioner.image }}:{{ .Values.provisioner.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODE_NAME
          valueFrom: 
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENEBS_MONITOR_URL
          value: "{{ .Values.provisioner.monitorurl }}"
        - name: OPENEBS_MONITOR_VOLKEY
          value: "{{ .Values.provisioner.monitorvolkey }}"
        - name: MAYA_PORTAL_URL
          value: "{{ .Values.provisioner.mayaportalurl }}"
