kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-anf-controller
  namespace: kube-system
spec:
  serviceName: csi-anf-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-anf-controller
    spec:
      serviceAccount: csi-anf-controller
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.0
          args:
            - "--provisioner=anf.csi.netapp.com"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-anf-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--subscriptionid=$(AZURE_SUBSCRIPTION_ID)"
            - "--tenantid=$(AZURE_TENANT_ID)"
            - "--clientid=$(AZURE_CLIENT_ID)"
            - "--clientsecret=$(AZURE_CLIENT_SECRET)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "anf-csi-driver.fullname" . }}
                  key: azure-subscription-id
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "anf-csi-driver.fullname" . }}
                  key: azure-tenant-id
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "anf-csi-driver.fullname" . }}
                  key: azure-client-id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "anf-csi-driver.fullname" . }}
                  key: azure-client-secret
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
