kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-anf-controller
  namespace: kube-system
spec:
  serviceName: csi-anf-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-anf-controller
    spec:
      serviceAccount: csi-anf-controller
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.0
          args:
            - "--provisioner=anf.csi.netapp.com"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-anf-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args :
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--subscription=$(ANF_API_SUB)"
            - "--tenant=$(ANF_API_TENANT)"
            - "--clientkey=$(ANF_API_KEY)"
            - "--clientsecret=$(ANF_API_SECRET)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: ANF_API_SUB
              valueFrom:
                secretKeyRef:
                  name: netapp
                  key: anf-api-sub
            - name: ANF_API_TENANT
              valueFrom:
                secretKeyRef:
                  name: netapp
                  key: anf-api-tenant
            - name: ANF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: netapp
                  key: anf-api-key
            - name: ANF_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: netapp
                  key: anf-api-secret
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}    