---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-trident
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: netapp-cvs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: netapp.io/trident
parameters:
  backendType: "aws-cvs"
