apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: {{ template "fullname" . }}
  name: alertmanager-{{ template "fullname" . }}
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: {{ template "fullname" . }}
