apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    alertmanager: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  version: {{ .Values.alertmanager.version }}
