{{ if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fullname" . }}-kube-state-metrics
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}
{{ end }}
