apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}-kube-state-metrics
    k8s-app: kube-state-metrics
  name: {{ template "fullname" . }}-kube-state-metrics
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}-kube-state-metrics
