apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    prometheus: {{ template "fullname" . }}
    app: prometheus
spec:
  replicas:  {{ .Values.prometheus.replicas }}
  baseImage: {{ .Values.prometheus.baseImage }}
  version: {{ .Values.prometheus.version }}
  retention: {{ .Values.prometheus.retention }}
  {{- if not .Values.prometheus.storageUseEmptyDir }}
  storage: {{ .Values.prometheus.storage }}
  {{- end }}
  serviceAccountName: {{ template "fullname" . }}
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-apps, operator: Exists}
  ruleSelector:
    matchLabels:
      role: {{ template "fullname" . }}-rulefiles
      prometheus: {{ template "fullname" . }}
  resources:
{{ toYaml .Values.prometheus.resources | indent 4 }}
  alerting:
    alertmanagers:
    - namespace: {{ .Release.Namespace }}
      name:  alertmanager-{{ template "fullname" . }}
      port: web
{{- if not .Values.prometheus.useEmptyDirStorage   }}
  storage:
{{ toYaml .Values.prometheus.storage | indent 4 }}
{{ end }}
