apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fullname" . }}-prometheus
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    prometheus: {{ template "fullname" . }}
spec:
  endpoints:
  - port: web
  selector:
    matchExpressions:
    - {key: prometheus, operator: In, values: [ {{ template "fullname" . }} ]}
