{{ if .Values.ingress.enabled | default false }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    prometheus: {{ template "fullname" . }}
spec:
  rules:
  - host:  {{ template "fullname" . }}.{{ .Release.Namespace}}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: web
{{ end }}
