apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    prometheus: {{ template "fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
      prometheus: {{ template "fullname" . }}
