apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "fullname" . }}-alertmanager
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    alertmanager: main
spec:
  endpoints:
  - port: web
  selector:
    matchExpressions:
    - {key: alertmanager, operator: In, values: [main]}
