apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: {{ template "fullname" . }}-metrics-any-ns
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-apps: http
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
    - {key: {{ .Values.serviceMonitor.metricsAnyNamespace.matchLabel }}, operator: Equals, value: {{ .Values.serviceMonitor.metricsAnyNamespace.matchValue }}}
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    interval: 15s
