# Default values for cloudflare-warp-ingress.

replicaCount: 2

image:
  repository: quay.io/stackpoint/warp-controller
  tag: 0.4.0
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  install: true
  serviceAccount: cloudflare-warp
  roleName: cloudflare-warp

# The secret contains the base64-encoded origin certificate for your cloudflare domain.
# Set the install flag false to configure manually in the cluster later.
# See https://warp.cloudflare.com/quickstart/quickstart/ for information on
# obtaining the origin certificate
secret:
  install: false
  domain: example.co
  certificate_b64: LS0tLS1CRUdJT...insert base64-encoded certificate here