{{- if eq .Values.objectStore.provider "aws-s3" }}
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: {{ .Values.configNamespace }}
  name: default
persistentVolumeProvider:
  name: {{ .Values.cluster.provider }}
  config:
    region: {{ .Values.cluster.region }}
backupStorageProvider:
  name: aws
  bucket: {{ .Values.objectStore.bucket }}
  config:
    region: {{ .Values.objectStore.region }}
backupSyncPeriod: {{ .Values.backupSyncPeriod }}
gcSyncPeriod: {{ .Values.gcSyncPeriod }}
scheduleSyncPeriod: {{ .Values.scheduleSyncPeriod }}
restoreOnlyMode: false
{{- end }}
