{{- if eq .Values.objectStore.provider "azure-storage" }}
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: {{ .Values.configNamespace }}
  name: default
persistentVolumeProvider:
  name: {{ .Values.cluster.provider }}
  config:
    location: {{ .Values.cluster.location }}
    apiTimeout: {{ .Values.cluster.apiTimeout }}
backupStorageProvider:
  name: azure
  bucket: {{ .Values.objectStore.bucket }}
backupSyncPeriod: {{ .Values.backupSyncPeriod }}
gcSyncPeriod: {{ .Values.gcSyncPeriod }}
scheduleSyncPeriod: {{ .Values.scheduleSyncPeriod }}
restoreOnlyMode: false
{{- end }}
