{{- if eq .Values.objectStoreProvider "azure" }}
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: {{ .Values.configNamespace }}
  name: default
persistentVolumeProvider:
  name: {{ .Values.clusterProvider }}
  config:
    region: {{ .Values.region }}
backupStorageProvider:
  name: azure
  bucket: {{ .Values.objectStoreBucket }}
  config:
    region: {{ .Values.region }}
backupSyncPeriod: {{ .Values.backupSyncPeriod }}
gcSyncPeriod: {{ .Values.gcSyncPeriod }}
scheduleSyncPeriod: {{ .Values.scheduleSyncPeriod }}
restoreOnlyMode: false
{{- end }}
