{{- if ne .Values.objectStore.provider "azure-storage" }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: {{ .Values.serverNamespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  AZURE_SUBSCRIPTION_ID: {{ .Values.objectStore.azureSubscriptionID }}
  AZURE_TENANT_ID: {{ .Values.objectStore.azureTenantID }}
  AZURE_RESOURCE_GROUP: {{ .Values.objectStore.azureResourceGroup | quote }}
  AZURE_CLIENT_ID: {{ .Values.objectStore.azureClientID | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.objectStore.azureClientSecret | quote }}
  AZURE_STORAGE_ACCOUNT_ID: {{ .Values.objectStore.azureStorageAccountID | quote }}
  AZURE_STORAGE_KEY: {{ .Values.objectStore.azureStorageKey | quote }}
{{- end }}
