apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: {{ .Values.serverNamespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  cloud: {{ .Values.cloudCredentials | b64enc | quote }}
