apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.serverNamespace }}
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: {{ .Values.image }}
          command:
            - /ark
          args:
            - server
            - --namespace
            - {{ .Values.configNamespace }}
          {{- if eq .Values.objectStore.provider "azure" }}
          volumeMounts:
            - name: plugins
              mountPath: /plugins
          envFrom:
            - secretRef:
                name: cloud-credentials
          {{- else }}
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
          env:
            {{- if eq .Values.objectStore.provider "aws-s3" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
            {{- else if eq .Values.objectStore.provider "google-cloud-storage" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
            {{- end }}
              value: /credentials/cloud
          {{- end }}
      volumes:
        {{- if ne .Values.objectStore.provider "azure" }}
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        {{- end }}
        - name: plugins
          emptyDir: {}
