{{- if eq .Values.objectStore.provider "gcp" }}
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: {{ .Values.configNamespace }}
  name: default
persistentVolumeProvider:
  name: {{ .Values.cluster.provider }}
  project: {{ .Values.objectStore.project }}
backupStorageProvider:
  name: gcp
  bucket: {{ .Values.objectStore.bucket }}
backupSyncPeriod: {{ .Values.backupSyncPeriod }}
gcSyncPeriod: {{ .Values.gcSyncPeriod }}
scheduleSyncPeriod: {{ .Values.scheduleSyncPeriod }}
restoreOnlyMode: false
{{- end }}
