global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'slack_notification'
  routes:
  - match:
      severity: notify
    receiver: slack_notification
receivers:
- name: slack_notification
  slack_configs:
  - api_url: "https://hooks.slack.com/services/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"
    channel: "@nate"
