apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  user: {{ .Values.auth.adminUser | default "admin" | b64enc }}
  password:  {{ .Values.auth.adminPassword | default "admin" | b64enc }}
