{{- if and .Values.istio.install (not .Release.IsInstall) -}}
{{ if .Values.ingress.enabled | default false }}
{{- $serviceName := include "istio.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}-{{ .Values.addons.zipkin.deployment.name }}
  labels:
{{ include "istio.labels.standard" . | indent 4 }}
spec:
  rules:
  - host:  {{ .Values.addons.zipkin.deployment.name }}.istio.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ $serviceName }}-{{ .Values.addons.zipkin.deployment.name }}
          servicePort: http
{{ end }}
{{- end -}}
