apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-agent
  labels:
    name: {{ template "fullname" . }}-agent
    app: {{ template "fullname" . }}
    weave-cloud-component: flux
    weave-flux-component: agent
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-agent
        app: {{ template "fullname" . }}
        weave-cloud-component: flux
        weave-flux-component: agent
    spec:
      serviceAccount: {{ template "fullname" . }}
      containers:
      - name: agent
        image: "{{ .Values.image.agentRepository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
{{ if .Values.cloud.enabled }}
          - '--token={{required "Weave Cloud token is missing, please make sure ServiceToken value is provided" .Values.cloud.serviceToken}}'
{{ else }}
          - '--fluxsvc-address=ws://localhost:3030'
      - name: server
        image: "{{ .Values.image.serverRepository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - '--database-source=file://fluxy.db'
{{ end }}     
        resources:
{{ toYaml .Values.resources | indent 10 }}
