{{ if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
  labels:
    name: {{ template "fullname" . }}
  rules:
    - apiGroups:
        - '*'
      resources:
        - '*'
      verbs:
        - '*'
    - nonResourceURLs:
        - '*'
      verbs:
        - '*'
---
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
kind: ClusterRoleBinding
  metadata:
    name: {{ template "fullname" . }}
    labels:
      name: {{ template "fullname" . }}
  roleRef:
    kind: ClusterRole
    name: {{ template "fullname" . }}
    apiGroup: rbac.authorization.k8s.io
  subjects:
    - kind: ServiceAccount
      name: {{ template "fullname" . }}
      namespace: {{ .Release.Namespace }}
{{ end }}
