

serverNamespace: heptio-ark-server
configNamespace: heptio-ark
image: gcr.io/heptio-images/ark:latest

# ****** Backup parameters
objectStore:
  # aws-s3, google-cloud-storage, azure-storage
  provider: ""
  region: ""
  bucket: ""
  # aws and gcp
  cloudCredentialsB64: ""
  #azure
  azureSubscriptionID: ""
  azureTenantID: ""
  azureResourceGroup: ""
  azureClientID: ""
  azureClientSecret: ""
  azureStorageAccountID: ""
  azureStorageKey: ""

  backupSyncPeriod: 60m0s
  gcSyncPeriod: 60m0s
  scheduleSyncPeriod: 1m0s

# Cluster paramerters

# Values: aws, gcp, azure
cluster:
  provider: ""
  # aws only
  region: ""
  # gcp only
  project: ""
  # azure only
  apiTimeout: ""
  location: ""
