{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-metrics
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-apps: {{ template "fullname" . }}
    {{ .Values.metrics.servicemonitor.label }}: {{ .Values.metrics.servicemonitor.value }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: {{ template "fullname" . }}
{{- end }}
