{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort:  {{ .Values.service.nodePort }}
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    nodePort:  {{ .Values.service.nodeTlsPort }}
    name: https
  selector:
    app: {{ template "fullname" . }}
{{ end }}
