# Default values for trident.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: netapp/trident
  tag: 19.04.0-beta.1
  pullPolicy: IfNotPresent
