{{ if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ .Values.rbac.roleName }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
{{ end }}
