---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trident
  labels:
    app: trident.netapp.io
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: trident.netapp.io
    spec:
      serviceAccount: trident
      containers:
      - name: trident-main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - /usr/local/bin/trident_orchestrator
        args:
        - -address=0.0.0.0
        - -etcd_v3
        - http://127.0.0.1:8001
        - -k8s_pod
        #- -k8s_api_server
        #- __KUBERNETES_SERVER__:__KUBERNETES_PORT__
        #- -debug
        livenessProbe:
          exec:
            command:
            - tridentctl
            - -s
            - 127.0.0.1:8000
            - get
            - backend
          failureThreshold: 2
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 90
      - name: etcd
        image: quay.io/coreos/etcd:v3.3.9
        command:
        - /usr/local/bin/etcd
        args:
        - -name
        - etcd1
        - -advertise-client-urls
        - http://127.0.0.1:8001
        - -listen-client-urls
        - http://127.0.0.1:8001
        - -initial-advertise-peer-urls
        - http://127.0.0.1:8002
        - -listen-peer-urls
        - http://127.0.0.1:8002
        - -data-dir
        - /var/etcd/data
        - -initial-cluster
        - etcd1=http://127.0.0.1:8002
        volumeMounts:
        - name: etcd-vol
          mountPath: /var/etcd/data
        livenessProbe:
          exec:
            command:
            - etcdctl
            - -endpoint=http://127.0.0.1:8001/
            - cluster-health
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 10
      volumes:
      - name: etcd-vol
        persistentVolumeClaim:
          claimName: trident
