---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: trident.netapp.io
  name: trident
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-trident
