---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trident.netapp.io
  name: trident
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: trident.netapp.io
  type: ClusterIP
