apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kubeturbo.fullname" . }}
  labels:
    k8s-app: {{ template "kubeturbo.fullname" . }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "kubeturbo"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.kubeturbo.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name | quote }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Chart.Name | quote }}
        version: "{{ .Values.kubeturbo.image.tag }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  "{{ .Values.kubeturbo.image.repository }}:{{ .Values.kubeturbo.image.tag }}"
          command:
            - /bin/kubeturbo
          args:
            - --v=2
            - --kubeconfig=/etc/kubernetes/kubeconfig
            - --turboconfig=/etc/kubeturbo/vmturboconfig
          volumeMounts:
          - name: kubeconfig
            mountPath: /etc/kubernetes
            readOnly: true
          - name: vmturboconfig
            mountPath: /etc/kubeturbo
            readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: {{ .Values.kubeconfig.secretName }}
      - name: vmturboconfig
        secret:
          secretName: {{ .Values.vmturboconfig.secretName }}
