apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vmturboconfig.secretName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  vmturboconfig: {{ include "vmturboconfig.contents" . | b64enc }}
