apiVersion: v1
name: traefik
version: 1.52.1
appVersion: 1.7.2
description: A Traefik based Kubernetes ingress controller with Let's Encrypt support
keywords:
- traefik
- ingress
- acme
- letsencrypt
home: http://traefik.io/
sources:
- https://github.com/containous/traefik
- https://github.com/krancour/charts/tree/master/traefik
maintainers:
- name: Kent Rancourt
  email: kent.rancourt@microsoft.com
engine: gotpl
icon: http://trusted-charts-logos.stackpoint.io/traefik.png
