requirements:
  ## Set nodes spec
  node: {} # {} if nothing set
#    count: 3
#    cpu: 2
#    ram: 2GB

  ## Set app spec
  app:
    rbac: false
    namespace: kube-system
    storage: true
    loadbalancer: true

    ## List of required values key names from values.yaml
    valuesEditRequired: # [] if nothing set
      - acme.email
