apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netapp-service-mesh-admin-role-binding-{{ .Release.Namespace }}
  labels:
    app: netapp-service-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netapp-service-mesh-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: netapp-service-mesh-service-account
    namespace: {{ .Release.Namespace }}
