apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netapp-service-mesh-{{ .Release.Namespace }}
  labels:
    app: netapp-service-mesh
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create"]

