{{- if .Values.secret.install }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-warp-cert
  labels:
    app: {{ template "cloudflare-warp-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    # future: label may be used for lookup
    cloudflare-warp/domain: {{ .Values.secret.domain }}
type: Opaque
data:
  cert.pem: |-
    {{ .Values.secret.certificate_b64 }}
{{ end }}