name: coredns
version: 0.3.0
description: CoreDNS is a DNS server that chains middleware and provides Kubernetes DNS Services
keywords:
- coredns
- dns
- kubedns
home: https://coredns.io
icon: http://trusted-charts-logos.stackpoint.io/coredns.png
sources:
- https://github.com/coredns/coredns
maintainers:
- name: Acaleph
  email: hello@acale.ph
- name: Shashidhara TD
  email: shashidhara.huawei@gmail.com
